document.writeln("<html lang=\'{{ .Site.Language.Lang }}\' dir=\'{{ $.Param \'contentdir\' | default \'zh\' }}\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("  <meta charset=utf-8>");
document.writeln("  <meta name=viewport content=\'width=device-width\'>");
document.writeln("  <meta name=theme-color content=\'#222\' media=\'(prefers-color-scheme: dark)\'>");
document.writeln("  <meta name=generator content=\'Hugo 0.118.2\'>");
document.writeln("  <link rel=\'shortcut icon\' type=image/x-icon href=/imgs/icons/favicon.png>");
document.writeln("  <link rel=icon type=image/x-icon href=/imgs/icons/favicon.png>");
document.writeln("  <link rel=icon type=image/png sizes=16x16 href=/imgs/icons/favicon.png>");
document.writeln("  <link rel=icon type=image/png sizes=32x32 href=/imgs/icons/favicon.png>");
document.writeln("  <link rel=apple-touch-icon sizes=180x180 href=/imgs/icons/favicon.png>");
document.writeln("  <meta itemprop=image content=\'https://myeeye.github.io/imgs/myee.png\'>");
document.writeln("  <link type=text/css rel=stylesheet href=https://cdn.staticfile.org/font-awesome/6.1.2/css/all.min.css>");
document.writeln("  <link type=text/css rel=stylesheet href=https://cdn.staticfile.org/animate.css/3.1.1/animate.min.css>");
document.writeln("  <link type=text/css rel=stylesheet href=https://cdn.staticfile.org/viewerjs/1.11.0/viewer.min.css>");
document.writeln("  <title>TBA</title>");
document.writeln("  <style type=\'text/css\'>");
document.writeln("    *{margin: 0;padding: 0;}");
document.writeln("    ::-webkit-scrollbar {display:none}");
document.writeln("    .btn {");
document.writeln("      display:inline-block;");
document.writeln("      padding:6px 12px;");
document.writeln("      margin-bottom:0;");
document.writeln("      text-align:center;");
document.writeln("      white-space:nowrap;");
document.writeln("      vertical-align:middle;");
document.writeln("      -ms-touch-action:manipulation;");
document.writeln("      touch-action:manipulation;");
document.writeln("      cursor:pointer;");
document.writeln("      -webkit-user-select:none;");
document.writeln("      -moz-user-select:none;");
document.writeln("      -ms-user-select:none;");
document.writeln("      user-select:none;");
document.writeln("      background-image:none;");
document.writeln("      border:1px solid transparent;");
document.writeln("      border-radius:4px");
document.writeln("    }");
document.writeln("    .btn:hover {");
document.writeln("      background-color: #ff3434;");
document.writeln("    }");
document.writeln("    .btn_blue {");
document.writeln("      padding: 10px;");
document.writeln("      text-align: center;");
document.writeln("      border-radius: 8px;");
document.writeln("      background: #1f1e33;");
document.writeln("      color: #fff;");
document.writeln("      letter-spacing: 3px;");
document.writeln("      border: 0;");
document.writeln("      font-size: 18px;");
document.writeln("      text-decoration-line: none;");
document.writeln("    }");
document.writeln("  </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("  <p align=\'center\' style=\'font-size:100px\'>别急</p>");
document.writeln("  <p align=\'center\' style=\'font-size:100px\'>还没写</p>");
document.writeln("  <p align=\'center\'><img src=\'/imgs/404cat.gif\' alt=\'\'></p>");
document.writeln("  <div align=\'center\'>");
document.writeln("    <a href=\'/\' class=\'btn btn-primary btn_blue\'>点击返回主页</a>");
document.writeln("  </div>");
document.writeln("</body>");
document.writeln("");